{
 "title": "Router Configuration Tool statistics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "router",
    "query": {
     "query": "label_values({job=\"rct\"},instance)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values({job=\"rct\",instance=\"$router\"},device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VPP vector rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_vpp_vector_rate{job=\"rct\",instance=\"$router\"}",
     "legendFormat": "vector {{vector}}"
    }
   ]
  },
  {
   "title": "Interface physical rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "node_network_physical_rate{job=\"rct\",instance=\"$router\"}*1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Interface traffic stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Network Traffic bps:  $interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"$interface\",instance=\"$router\"}[1m])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"$interface\",instance=\"$router\"}[1m])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic: all interfaces brief",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"rct\",instance=\"$router\"}[1m])*8",
     "legendFormat": "{{device}} - rx bps"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"rct\",instance=\"$router\"}[1m])*8",
     "legendFormat": "{{device}} - tx bps"
    },
    {
     "expr": "irate(node_network_receive_packets_total{job=\"rct\",instance=\"$router\"}[1m])",
     "legendFormat": "{{device}} - rx pps"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"rct\",instance=\"$router\"}[1m])",
     "legendFormat": "{{device}} - tx pps"
    },
    {
     "expr": "irate(node_network_receive_error_total{job=\"rct\",instance=\"$router\"}[1m])",
     "legendFormat": "{{device}} - rx err"
    },
    {
     "expr": "irate(node_network_transmit_error_total{job=\"rct\",instance=\"$router\"}[1m])",
     "legendFormat": "{{device}} - tx err"
    },
    {
     "expr": "irate(node_network_drop_total{job=\"rct\",instance=\"$router\"}[1m])",
     "legendFormat": "{{device}} - drops"
    }
   ]
  },
  {
   "title": "Network Traffic pps: $interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{device=\"$interface\",instance=\"$router\"}[1m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{device=\"$interface\",instance=\"$router\"}[1m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic err:  $interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_error_total{device=\"$interface\",instance=\"$router\"}[1m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_error_total{device=\"$interface\",instance=\"$router\"}[1m])",
     "legendFormat": "{{device}} - Transmit"
    },
    {
     "expr": "irate(node_network_drop_total{device=\"$interface\",instance=\"$router\"}[1m])",
     "legendFormat": "{{device}} - Drops"
    }
   ]
  }
 ]
}