{
 "title": "Router Configuration Tool statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interface",
    "query": {
     "query": "label_values({job=\"rct\"},device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VPP vector rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_vpp_vector_rate{job=\"rct\"}",
     "legendFormat": "vector {{vector}}"
    }
   ]
  },
  {
   "title": "Interface physical rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "node_network_physical_rate{job=\"rct\"}*1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Interface traffic stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Network Traffic - All interfaces",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"rct\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"rct\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets - All interfaces",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"rct\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"rct\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{device=\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{device=\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Errors - All interfaces",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_error_total{job=\"rct\"}[$__rate_interval])",
     "legendFormat": "{{device}} - RxErr"
    },
    {
     "expr": "irate(node_network_transmit_error_total{job=\"rct\"}[$__rate_interval])",
     "legendFormat": "{{device}} - TxErr"
    },
    {
     "expr": "irate(node_network_drop_total{job=\"rct\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Drops"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_error_total{device=\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_error_total{device=\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    },
    {
     "expr": "irate(node_network_drop_total{device=\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Drops"
    }
   ]
  }
 ]
}